// frontend-examen/src/components/Login.vue

<template>
  <div class="login-container">
    <form @submit.prevent="handleLogin">
      <div class="form-group">
        <label>DNI:</label>
        <input type="text" v-model="dni" required>
      </div>
      <div class="form-group">
        <label>Token:</label>
        <input type="password" v-model="token" required>
      </div>
      <button type="submit">Iniciar Sesión</button>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { SesionService } from '../services/sesionService';

export default defineComponent({
  name: 'Login',
  data() {
    return {
      dni: '',
      token: '',
      sesionService: new SesionService()
    }
  },
  methods: {
    async handleLogin() {
      const loggedIn = await this.sesionService.iniciarSesion(this.dni, this.token);
      if (loggedIn) {
        this.$emit('login-success');
      } else {
        alert('Error al iniciar sesión');
      }
    }
  }
});
</script>

<style scoped>
.login-container {
  max-width: 400px;
  margin: 0 auto;
  padding: 20px;
}

.form-group {
  margin-bottom: 15px;
}
</style>

// frontend-examen/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SesionService } from '../../services/sesion.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  dni: string = '';
  token: string = '';

  constructor(private sesionService: SesionService) {}

  async handleLogin(): Promise<void> {
    this.sesionService.iniciarSesion(this.dni, this.token)
      .subscribe({
        next: (success) => {
          if (success) {
            // Manejar login exitoso
          } else {
            alert('Error al iniciar sesión');
          }
        },
        error: () => alert('Error al iniciar sesión')
      });
  }
}

<div class="login-container">
  <form (ngSubmit)="handleLogin()">
    <div class="form-group">
      <label>DNI:</label>
      <input type="text" [(ngModel)]="dni" name="dni" required>
    </div>
    <div class="form-group">
      <label>Token:</label>
      <input type="password" [(ngModel)]="token" name="token" required>
    </div>
    <button type="submit">Iniciar Sesión</button>
  </form>
</div>
